<?php

/**
 * @file
 * hook theme dexp_flickr
 */

function dexp_flickr_theme($existing, $type, $theme, $path) {
    return array(
        'flickr' => array(
            'variables' => array(
                'flickr_source' => '',
                'flickr_id' => '',
                'flickr_num_photo' => '',
                'flickr_display' => '',
                'flickr_image_size' => '',
            ),
            'template' => 'dexp_flickr'
        ),
    );
}