module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  apigee_edge: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  context: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  devel_php: 0
  dexp_block: 0
  dexp_block_settings: 0
  dexp_builder: 0
  dexp_layerslider: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  fhir_apigee_cred_api: 0
  fhir_app: 0
  fhir_blocks: 0
  fhir_conformance_report: 0
  fhir_custom_api_form: 0
  fhir_customizations: 0
  fhir_datasets: 0
  fhir_google_sign: 0
  fhir_overview: 0
  fhir_rebranding: 0
  fhir_restapi: 0
  fhir_server: 0
  fhir_smart: 0
  fhir_swagger: 0
  field: 0
  field_collection: 0
  field_ui: 0
  file: 0
  file_link: 0
  filter: 0
  ghc_app_scopes_configurations: 0
  help: 0
  history: 0
  image: 0
  image_browser: 0
  key: 0
  kint: 0
  link: 0
  mail_login: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  payload_version: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  rest: 0
  rest_menu_items: 0
  restui: 0
  search: 0
  serialization: 0
  shortcode: 0
  shortcode_basic_tags: 0
  shortcut: 0
  smtp: 0
  social_api: 0
  social_auth: 0
  social_auth_google: 0
  swagger_ui_formatter: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  fhir_responsive_theme: 0
  mdc_theme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
