openapi: 3.0.1
info:
  title: HL7® FHIR® AllergyIntolerance resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
- url: https://org-env.apigee.net/v1/ghc/r4
tags:
- name: AllergyIntolerance
paths:
  /AllergyIntolerance:
    get:
      tags:
      - AllergyIntolerance
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
    put:
      tags:
        - AllergyIntolerance
      description: 'The conditional update interaction is used to update an existing AllergyIntolerance based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance Conditional Update
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.write
    post:
      tags:
      - AllergyIntolerance
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
            - patient/AllergyIntolerance.write
    delete:
      tags:
        - AllergyIntolerance
      description: 'The conditional delete interaction allows a client to delete AllergyIntolerance/AllergyIntolerances  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance Conditional Delete
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.write
  /AllergyIntolerance/{id}:
    get:
      tags:
      - AllergyIntolerance
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
            - patient/AllergyIntolerance.write
    put:
      tags:
      - AllergyIntolerance
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
            - patient/AllergyIntolerance.write
    delete:
      tags:
      - AllergyIntolerance
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
            - patient/AllergyIntolerance.write
  /AllergyIntolerance/{id}/_history:
    get:
      tags:
      - AllergyIntolerance
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
            - patient/AllergyIntolerance.write
  /AllergyIntolerance/_history:
    get:
      tags:
      - AllergyIntolerance
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
            - patient/AllergyIntolerance.write
  /AllergyIntolerance/{id}/_history/{vid}:
    get:
      tags:
      - AllergyIntolerance
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
            - patient/AllergyIntolerance.write
  /AllergyIntolerance/$meta:
    get:
      tags:
        - AllergyIntolerance
      description: 'Retrieves a summary of the profiles, tags, and security labels for AllergyIntolerances.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerances Metadata
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
  /AllergyIntolerance/{id}/$meta:
    get:
      tags:
        - AllergyIntolerance
      description: 'Retrieves a summary of the profiles, tags, and security labels for given AllergyIntolerance resource.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance Metadata
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
  /AllergyIntolerance/{id}/_history/{vid}/$meta:
    get:
      tags:
        - AllergyIntolerance
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the AllergyIntolerance.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance Version based Metadata
      security: 
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
  /AllergyIntolerance/{id}/{type}:
    get:
      tags:
        - AllergyIntolerance
      description: 'Search the specified resource type in AllergyIntolerance compartment.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: ' Compartment Search'
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
  /AllergyIntolerance/_search:
    post:
      tags:
        - AllergyIntolerance
      description: 'This interaction searches a set of AllergyIntolerances based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerances Search using POST
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.read
  /AllergyIntolerance/{id}/$meta-add:
    post:
      tags:
        - AllergyIntolerance
      description: 'Add a metadata info AllergyIntolerance with specified id.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: Add AllergyIntolerance metadata
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.write
  /AllergyIntolerance/{id}/_history/{vid}/$meta-add:
    post:
      tags:
        - AllergyIntolerance
      description: 'Add metadata info to specified AllergyIntolerance resource.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: Add AllergyIntolerance Version based Metadata
      security:
        - SetOAuth2AccessToken:
            - patient/AllergyIntolerance.write
components:
  securitySchemes:
    OAuthV2B2C:
      type: oauth2
      description: Security scheme for B2C flow using authorization code flow.
      flows:
        authorizationCode:
          authorizationUrl: 'https://org-env.apigee.net/oauth/v2/authorize'
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken'
          scopes:
            patient/AllergyIntolerance.read: Read permissions for AllergyIntolerance demographics.
            patient/AllergyIntolerance.write: Write permissions for AllergyIntolerance demographics.
    SetOAuth2AccessToken:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/AllergyIntolerance.read: Read permissions for AllergyIntolerance demographics.
            patient/AllergyIntolerance.write: Write permissions for AllergyIntolerance demographics.
