openapi: 3.0.1
info:
  title: HL7® FHIR® CarePlan resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
- url: https://org-env.apigee.net/v1/ghc/r4
tags:
- name: CarePlan
paths:
  /CarePlan:
    get:
      tags:
      - CarePlan
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
    put:
      tags:
        - CarePlan
      description: 'The conditional update interaction is used to update an existing CarePlan based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan Conditional Update
      security:
        - OAuthV2B2B:
            - patient/CarePlan.write
    post:
      tags:
      - CarePlan
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
    delete:
      tags:
        - CarePlan
      description: 'The conditional delete interaction allows a client to delete CarePlan/CarePlans  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/CarePlan.write
  /CarePlan/{id}:
    get:
      tags:
      - CarePlan
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
    put:
      tags:
      - CarePlan
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
    delete:
      tags:
      - CarePlan
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
  /CarePlan/{id}/_history:
    get:
      tags:
      - CarePlan
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
  /CarePlan/_history:
    get:
      tags:
      - CarePlan
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
  /CarePlan/{id}/_history/{vid}:
    get:
      tags:
      - CarePlan
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
  /CarePlan/$meta:
    get:
      tags:
        - CarePlan
      description: 'Retrieves a summary of the profiles, tags, and security labels for CarePlans.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlans Metadata
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
  /CarePlan/{id}/$meta:
    get:
      tags:
        - CarePlan
      description: 'Retrieves a summary of the profiles, tags, and security labels for given CarePlan resource.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan Metadata
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
  /CarePlan/{id}/_history/{vid}/$meta:
    get:
      tags:
        - CarePlan
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the CarePlan.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
  /CarePlan/{id}/{type}:
    get:
      tags:
        - CarePlan
      description: 'Search the specified resource type in CarePlan compartment.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
  /CarePlan/_search:
    post:
      tags:
        - CarePlan
      description: 'This interaction searches a set of CarePlans based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlans Search using POST
      security:
        - OAuthV2B2B:
            - patient/CarePlan.read
            - patient/CarePlan.write
  /CarePlan/{id}/$meta-add:
    post:
      tags:
        - CarePlan
      description: 'Add a metadata info CarePlan with specified id.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: Add CarePlan metadata
      security:
        - OAuthV2B2B:
            - patient/CarePlan.write
  /CarePlan/{id}/_history/{vid}/$meta-add:
    post:
      tags:
        - CarePlan
      description: 'Add metadata info to specified CarePlan resource.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: Add CarePlan Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/CarePlan.write
components:
  securitySchemes:
    OAuthV2B2C:
      type: oauth2
      description: Security scheme for B2C flow using authorization code flow.
      flows:
        authorizationCode:
          authorizationUrl: 'https://org-env.apigee.net/oauth/v2/authorize'
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken'
          scopes:
            patient/CarePlan.read: Read permissions for CarePlan demographics.
            patient/CarePlan.write: Write permissions for CarePlan demographics.
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/CarePlan.read: Read permissions for CarePlan demographics.
            patient/CarePlan.write: Write permissions for CarePlan demographics.
