openapi: 3.0.1
info:
  title: HL7® FHIR® ClaimResponse resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
- url: https://org-env.apigee.net/v1/ghc/r4
tags:
- name: ClaimResponse
paths:
  /ClaimResponse:
    get:
      tags:
      - ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
    put:
      tags:
        - ClaimResponse
      description: 'The conditional update interaction is used to update an existing ClaimResponse based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Conditional Update
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.write
    post:
      tags:
      - ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
    delete:
      tags:
        - ClaimResponse
      description: 'The conditional delete interaction allows a client to delete ClaimResponse/ClaimResponse  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.write
  /ClaimResponse/{id}:
    get:
      tags:
      - ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
    put:
      tags:
      - ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
    delete:
      tags:
      - ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/{id}/_history:
    get:
      tags:
      - ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/_history:
    get:
      tags:
      - ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/{id}/_history/{vid}:
    get:
      tags:
      - ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/$meta:
    get:
      tags:
        - ClaimResponse
      description: 'Retrieves a summary of the profiles, tags, and security labels for ClaimResponse.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/{id}/$meta:
    get:
      tags:
        - ClaimResponse
      description: 'Retrieves a summary of the profiles, tags, and security labels for given ClaimResponse resource.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponses Metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/{id}/_history/{vid}/$meta:
    get:
      tags:
        - ClaimResponse
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the ClaimResponse.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/{id}/{type}:
    get:
      tags:
        - ClaimResponse
      description: 'Search the specified resource type in ClaimResponse compartment.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/_search:
    post:
      tags:
        - ClaimResponse
      description: 'This interaction searches a set of ClaimResponse based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Search using POST
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/{id}/$meta-add:
    post:
      tags:
        - ClaimResponse
      description: 'Add a metadata info ClaimResponse with specified id.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: Add ClaimResponse metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
  /ClaimResponse/{id}/_history/{vid}/$meta-add:
    post:
      tags:
        - ClaimResponse
      description: 'Add metadata info to specified ClaimResponse resource.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: Add ClaimResponse Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
            - patient/ClaimResponse.write
components:
  securitySchemes:
    OAuthV2B2C:
      type: oauth2
      description: Security scheme for B2C flow using authorization code flow.
      flows:
        authorizationCode:
          authorizationUrl: 'https://org-env.apigee.net/oauth/v2/authorize'
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken'
          scopes:
            patient/ClaimResponse.read: Read permissions for ClaimResponse demographics.
            patient/ClaimResponse.write: Write permissions for ClaimResponse demographics.
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/ClaimResponse.read: Read permissions for ClaimResponse demographics.
            patient/ClaimResponse.write: Write permissions for ClaimResponse demographics.
