openapi: 3.0.1
info:
  title: HL7® FHIR® Claim resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
- url: https://org-env.apigee.net/v1/ghc/r4
tags:
- name: Claim
paths:
  /Claim:
    get:
      tags:
      - Claim
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
    put:
      tags:
        - Claim
      description: 'The conditional update interaction is used to update an existing Claim based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/claim.html''>FHIR documentation for Claim.</a></p>'
      operationId: Claim Conditional Update
      security:
        - OAuthV2B2B:
            - patient/Claim.write
    post:
      tags:
      - Claim
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
    delete:
      tags:
        - Claim
      description: 'The conditional delete interaction allows a client to delete Claim/Claim  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/claim.html''>FHIR documentation for Claim.</a></p>'
      operationId: Claim Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/Claim.write
  /Claim/{id}:
    get:
      tags:
      - Claim
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
    put:
      tags:
      - Claim
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
    delete:
      tags:
      - Claim
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
  /Claim/{id}/_history:
    get:
      tags:
      - Claim
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
  /Claim/_history:
    get:
      tags:
      - Claim
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
  /Claim/{id}/_history/{vid}:
    get:
      tags:
      - Claim
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
  /Claim/$meta:
    get:
      tags:
        - Claim
      description: 'Retrieves a summary of the profiles, tags, and security labels for Claim.<p><a href = ''https://www.hl7.org/fhir/claim.html''>FHIR documentation for Claim.</a></p>'
      operationId: Claim Metadata
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
  /Claim/{id}/$meta:
    get:
      tags:
        - Claim
      description: 'Retrieves a summary of the profiles, tags, and security labels for given Claim resource.<p><a href = ''https://www.hl7.org/fhir/claim.html''>FHIR documentation for Claim.</a></p>'
      operationId: Claims Metadata
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
  /Claim/{id}/_history/{vid}/$meta:
    get:
      tags:
        - Claim
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the Claim.<p><a href = ''https://www.hl7.org/fhir/claim.html''>FHIR documentation for Claim.</a></p>'
      operationId: Claim Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
  /Claim/{id}/{type}:
    get:
      tags:
        - Claim
      description: 'Search the specified resource type in Claim compartment.<p><a href = ''https://www.hl7.org/fhir/Claim.html''>FHIR documentation for Claim.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
  /Claim/_search:
    post:
      tags:
        - Claim
      description: 'This interaction searches a set of Claim based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/claim.html''>FHIR documentation for Claim.</a></p>'
      operationId: Claim Search using POST
      security:
        - OAuthV2B2B:
            - patient/Claim.read
  /Claim/{id}/$meta-add:
    post:
      tags:
        - Claim
      description: 'Add a metadata info Claim with specified id.<p><a href = ''https://www.hl7.org/fhir/claim.html''>FHIR documentation for Claim.</a></p>'
      operationId: Add Claim metadata
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
  /Claim/{id}/_history/{vid}/$meta-add:
    post:
      tags:
        - Claim
      description: 'Add metadata info to specified Claim resource.<p><a href = ''https://www.hl7.org/fhir/claim.html''>FHIR documentation for Claim.</a></p>'
      operationId: Add Claim Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Claim.read
            - patient/Claim.write
components:
  securitySchemes:
    OAuthV2B2C:
      type: oauth2
      description: Security scheme for B2C flow using authorization code flow.
      flows:
        authorizationCode:
          authorizationUrl: 'https://org-env.apigee.net/oauth/v2/authorize'
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken'
          scopes:
            patient/Claim.read: Read permissions for Claim demographics.
            patient/Claim.write: Write permissions for Claim demographics.
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Claim.read: Read permissions for Claim demographics.
            patient/Claim.write: Write permissions for Claim demographics.
