openapi: 3.0.1
info:
  title: HL7® FHIR® Composition resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
- url: https://org-env.apigee.net/v1/ghc/r4
tags:
- name: Composition
paths:
  /Composition:
    get:
      tags:
      - Composition
      security:
        - OAuthV2B2B:
            - patient/Composition.read
            - patient/Composition.write
    put:
      tags:
        - Composition
      security:
        - OAuthV2B2B:
            - patient/Composition.read
    post:
      tags:
      - Composition
      security:
        - OAuthV2B2B:
            - patient/Composition.read
            - patient/Composition.write
    delete:
      tags:
        - Composition
      description: 'The conditional delete interaction allows a client to delete Composition/Composition  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/composition.html''>FHIR documentation for Composition.</a></p>'
      operationId: Composition Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/Composition.write
  /Composition/{id}:
    get:
      tags:
      - Composition
      security:
        - OAuthV2B2B:
            - patient/Composition.read
            - patient/Composition.write
    put:
      tags:
      - Composition
      security:
        - OAuthV2B2B:
            - patient/Composition.read
            - patient/Composition.write
    delete:
      tags:
      - Composition
      security:
        - OAuthV2B2B:
            - patient/Composition.read
            - patient/Composition.write
  /Composition/{id}/_history:
    get:
      tags:
      - Composition
      security:
        - OAuthV2B2B:
            - patient/Composition.read
            - patient/Composition.write
  /Composition/_history:
    get:
      tags:
      - Composition
      security:
        - OAuthV2B2B:
            - patient/Composition.read
            - patient/Composition.write
  /Composition/{id}/_history/{vid}:
    get:
      tags:
      - Composition
      security:
        - OAuthV2B2B:
            - patient/Composition.read
            - patient/Composition.write
components:
  securitySchemes:
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Composition.read: Read permissions for Composition demographics.
            patient/Composition.write: Write permissions for Composition demographics.
