openapi: 3.0.1
info:
  title: HL7® FHIR® Condition resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
- url: https://org-env.apigee.net/v1/ghc/r4
tags:
- name: Condition
paths:
  /Condition:
    get:
      tags:
      - Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
    put:
      tags:
        - Condition
      description: 'The conditional update interaction is used to update an existing Condition based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition Conditional Update
      security:
        - OAuthV2B2B:
            - patient/Condition.write
    post:
      tags:
      - Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
    delete:
      tags:
        - Condition
      description: 'The conditional delete interaction allows a client to delete Condition/Conditions  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/Condition.write
  /Condition/{id}:
    get:
      tags:
      - Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
    put:
      tags:
      - Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
    delete:
      tags:
      - Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/{id}/_history:
    get:
      tags:
      - Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/_history:
    get:
      tags:
      - Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/{id}/_history/{vid}:
    get:
      tags:
      - Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/$meta:
    get:
      tags:
        - Condition
      description: 'Retrieves a summary of the profiles, tags, and security labels for Conditions.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Conditions Metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/{id}/$meta:
    get:
      tags:
        - Condition
      description: 'Retrieves a summary of the profiles, tags, and security labels for given Condition resource.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition Metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/{id}/_history/{vid}/$meta:
    get:
      tags:
        - Condition
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the Condition.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/{id}/{type}:
    get:
      tags:
        - Condition
      description: 'Search the specified resource type in Condition compartment.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/_search:
    post:
      tags:
        - Condition
      description: 'This interaction searches a set of Conditions based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Conditions Search using POST
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/{id}/$meta-add:
    post:
      tags:
        - Condition
      description: 'Add a metadata info Condition with specified id.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Add Condition metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
  /Condition/{id}/_history/{vid}/$meta-add:
    post:
      tags:
        - Condition
      description: 'Add metadata info to specified Condition resource.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Add Condition Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.read
            - patient/Condition.write
components:
  securitySchemes:
    OAuthV2B2C:
      type: oauth2
      description: Security scheme for B2C flow using authorization code flow.
      flows:
        authorizationCode:
          authorizationUrl: 'https://org-env.apigee.net/oauth/v2/authorize'
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken'
          scopes:
            patient/Condition.read: Read permissions for Condition demographics.
            patient/Condition.write: Write permissions for Condition demographics.
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Condition.read: Read permissions for Condition demographics.
            patient/Condition.write: Write permissions for Condition demographics.
