openapi: 3.0.1
info:
  title: HL7® FHIR® ExplanationOfBenefit resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
- url: https://org-env.apigee.net/v1/ghc/r4
tags:
- name: ExplanationOfBenefit
paths:
  /ExplanationOfBenefit:
    get:
      tags:
      - ExplanationOfBenefit
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
    put:
      tags:
        - ExplanationOfBenefit
      description: 'The conditional update interaction is used to update an existing ExplanationOfBenefit based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/explanationofbenefit.html''>FHIR documentation for ExplanationOfBenefit.</a></p>'
      operationId: ExplanationOfBenefit Conditional Update
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
    post:
      tags:
      - ExplanationOfBenefit
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
    delete:
      tags:
        - ExplanationOfBenefit
      description: 'The conditional delete interaction allows a client to delete /ExplanationOfBenefit  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/explanationofbenefit.html''>FHIR documentation for ExplanationOfBenefit.</a></p>'
      operationId: ExplanationOfBenefit Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/{id}:
    get:
      tags:
      - ExplanationOfBenefit
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
    put:
      tags:
      - ExplanationOfBenefit
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
    delete:
      tags:
      - ExplanationOfBenefit
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/{id}/_history:
    get:
      tags:
      - ExplanationOfBenefit
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/_history:
    get:
      tags:
      - ExplanationOfBenefit
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/{id}/_history/{vid}:
    get:
      tags:
      - ExplanationOfBenefit
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/$meta:
    get:
      tags:
        - ExplanationOfBenefit
      description: 'Retrieves a summary of the profiles, tags, and security labels for ExplanationOfBenefit.<p><a href = ''https://www.hl7.org/fhir/explanationofbenefit.html''>FHIR documentation for ExplanationOfBenefit.</a></p>'
      operationId: ExplanationOfBenefit Metadata
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/{id}/$meta:
    get:
      tags:
        - ExplanationOfBenefit
      description: 'Retrieves a summary of the profiles, tags, and security labels for given ExplanationOfBenefit resource.<p><a href = ''https://www.hl7.org/fhir/explanationofbenefit.html''>FHIR documentation for ExplanationOfBenefit.</a></p>'
      operationId: ExplanationOfBenefits Metadata
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/{id}/_history/{vid}/$meta:
    get:
      tags:
        - ExplanationOfBenefit
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the ExplanationOfBenefit.<p><a href = ''https://www.hl7.org/fhir/explanationofbenefit.html''>FHIR documentation for ExplanationOfBenefit.</a></p>'
      operationId: ExplanationOfBenefit Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/{id}/{type}:
    get:
      tags:
        - ExplanationOfBenefit
      description: 'Search the specified resource type in ExplanationOfBenefit compartment.<p><a href = ''https://www.hl7.org/fhir/explanationofbenefit.html''>FHIR documentation for ExplanationOfBenefit.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/_search:
    post:
      tags:
        - ExplanationOfBenefit
      description: 'This interaction searches a set of ExplanationOfBenefit based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/explanationofbenefit.html''>FHIR documentation for ExplanationOfBenefit.</a></p>'
      operationId: ExplanationOfBenefit Search using POST
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.read
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/{id}/$meta-add:
    post:
      tags:
        - ExplanationOfBenefit
      description: 'Add a metadata info ExplanationOfBenefit with specified id.<p><a href = ''https://www.hl7.org/fhir/explanationofbenefit.html''>FHIR documentation for ExplanationOfBenefit.</a></p>'
      operationId: Add ExplanationOfBenefit metadata
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.write
  /ExplanationOfBenefit/{id}/_history/{vid}/$meta-add:
    post:
      tags:
        - ExplanationOfBenefit
      description: 'Add metadata info to specified ExplanationOfBenefit resource.<p><a href = ''https://www.hl7.org/fhir/explanationofbenefit.html''>FHIR documentation for ExplanationOfBenefit.</a></p>'
      operationId: Add ExplanationOfBenefit Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/ExplanationOfBenefit.write
components:
  securitySchemes:
    OAuthV2B2C:
      type: oauth2
      description: Security scheme for B2C flow using authorization code flow.
      flows:
        authorizationCode:
          authorizationUrl: 'https://org-env.apigee.net/oauth/v2/authorize'
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken'
          scopes:
            patient/ExplanationOfBenefit.read: Read permissions for ExplanationOfBenefit demographics.
            patient/ExplanationOfBenefit.write: Write permissions for ExplanationOfBenefit demographics.
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/ExplanationOfBenefit.read: Read permissions for ExplanationOfBenefit demographics.
            patient/ExplanationOfBenefit.write: Write permissions for ExplanationOfBenefit demographics.
