openapi: 3.0.1
info:
  title: HL7® FHIR® Patient resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
- url: https://org-env.apigee.net/v1/ghc/r4
tags:
- name: Patient
paths:
  /Patient:
    get:
      tags:
      - Patient
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
    put:
      tags:
        - Patient
      description: 'The conditional update interaction is used to update an existing Patient based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Patient Conditional Update
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
    post:
      tags:
      - Patient
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
    delete:
      tags:
        - Patient
      description: 'The conditional delete interaction allows a client to delete Patient/Patients  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Patient Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/{id}:
    get:
      tags:
      - Patient
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
    put:
      tags:
      - Patient
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
    delete:
      tags:
      - Patient
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/{id}/_history:
    get:
      tags:
      - Patient
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/_history:
    get:
      tags:
      - Patient
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/{id}/_history/{vid}:
    get:
      tags:
      - Patient
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/$meta:
    get:
      tags:
        - Patient
      description: 'Retrieves a summary of the profiles, tags, and security labels for Patients.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Patients Metadata
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/{pid}/$meta:
    get:
      tags:
        - Patient
      description: 'Retrieves a summary of the profiles, tags, and security labels for given Patient resource.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Patient Metadata
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/{pid}/_history/{vid}/$meta:
    get:
      tags:
        - Patient
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the Patient.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Patient Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/{pid}/{type}:
    get:
      tags:
        - Patient
      description: 'Search the specified resource type in Patient compartment.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/_search:
    post:
      tags:
        - Patient
      description: 'This interaction searches a set of Patients based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Patients Search using POST
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/{pid}/$meta-add:
    post:
      tags:
        - Patient
      description: 'Add a metadata info Patient with specified id.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Add Patient metadata
      security:
        - OAuthV2B2B:
            - patient/Patient.write
  /Patient/{pid}/_history/{vid}/$meta-add:
    post:
      tags:
        - Patient
      description: 'Add metadata info to specified Patient resource.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Add Patient Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/$everything:
    get:
      tags:
        - Patient
      description: 'Returns all the information related to Patient resource.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Fetch Patients Record
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
  /Patient/{pid}/$everything:
    get:
      tags:
        - Patient
      description: 'Returns all the information related to a specific Patient resource.<p><a href = ''https://www.hl7.org/fhir/patient.html''>FHIR documentation for Patient.</a></p>'
      operationId: Fetch Patient Record
      security:
        - OAuthV2B2B:
            - patient/Patient.read
            - patient/Patient.write
components:
  securitySchemes:
    OAuthV2B2C:
      type: oauth2
      description: Security scheme for B2C flow using authorization code flow.
      flows:
        authorizationCode:
          authorizationUrl: 'https://org-env.apigee.net/oauth/v2/authorize'
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken'
          scopes:
            patient/Patient.read: Read permissions for Patient demographics.
            patient/Patient.write: Write permissions for Patient demographics.
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Patient.read: Read permissions for Patient demographics.
            patient/Patient.write: Write permissions for Patient demographics.
