dstu2: 'https://healthapix-demo-dev.apigee.net/v1/dstu2/DSTU2_9FD17CB4-9835-46BB-BDD4-C84A014CEEA4/metadata'
stu3: 'https://healthapix-demo-dev.apigee.net/v1/stu3/STU3_F920123C-66A6-4AEC-963D-023ED07D4932/metadata'
r4: 'https://healthapix-demo-dev.apigee.net/v1/r4/R4_44508497-b8ef-41d9-a308-47f9f45cad2e/metadata'
