AllergyIntolerance___showToPatientScope: 1
AllergyIntolerance___showToUserScope: 1
AllergyIntolerance___showWritePatient: 1
AllergyIntolerance___showReadPatient: 1
AllergyIntolerance___showWriteUser: 1
AllergyIntolerance___showReadUser: 1
Observation___showToPatientScope: 1
Observation___showToUserScope: 1
Observation___showWritePatient: 1
Observation___showReadPatient: 1
Observation___showWriteUser: 1
Observation___showReadUser: 1
Claim___showToPatientScope: 1
Claim___showToUserScope: 1
Claim___showWritePatient: 1
Claim___showReadPatient: 1
Claim___showWriteUser: 1
Claim___showReadUser: 1
Schedule___showToPatientScope: 1
Schedule___showToUserScope: 1
Schedule___showWritePatient: 1
Schedule___showReadPatient: 1
Schedule___showWriteUser: 1
Schedule___showReadUser: 1
CarePlan___showToPatientScope: 1
CarePlan___showToUserScope: 1
CarePlan___showWritePatient: 1
CarePlan___showReadPatient: 1
CarePlan___showWriteUser: 1
CarePlan___showReadUser: 1
DiagnosticReport___showToPatientScope: 1
DiagnosticReport___showToUserScope: 1
DiagnosticReport___showWritePatient: 1
DiagnosticReport___showReadPatient: 1
DiagnosticReport___showWriteUser: 1
DiagnosticReport___showReadUser: 1
Coverage___showToPatientScope: 1
Coverage___showToUserScope: 1
Coverage___showWritePatient: 1
Coverage___showReadPatient: 1
Coverage___showWriteUser: 1
Coverage___showReadUser: 1
ExplanationOfBenefit___showToPatientScope: 1
ExplanationOfBenefit___showToUserScope: 1
ExplanationOfBenefit___showWritePatient: 1
ExplanationOfBenefit___showReadPatient: 1
ExplanationOfBenefit___showWriteUser: 1
ExplanationOfBenefit___showReadUser: 1
MedicationOrder___showToPatientScope: 1
MedicationOrder___showToUserScope: 1
MedicationOrder___showWritePatient: 1
MedicationOrder___showReadPatient: 1
MedicationOrder___showWriteUser: 1
MedicationOrder___showReadUser: 1
DocumentReference___showToPatientScope: 1
DocumentReference___showToUserScope: 1
DocumentReference___showWritePatient: 1
DocumentReference___showReadPatient: 1
DocumentReference___showWriteUser: 1
DocumentReference___showReadUser: 1
Encounter___showToPatientScope: 1
Encounter___showToUserScope: 1
Encounter___showWritePatient: 1
Encounter___showReadPatient: 1
Encounter___showWriteUser: 1
Encounter___showReadUser: 1
Patient___showToPatientScope: 1
Patient___showToUserScope: 1
Patient___showWritePatient: 1
Patient___showReadPatient: 1
Patient___showWriteUser: 1
Patient___showReadUser: 1
Endpoint___showToPatientScope: 1
Endpoint___showToUserScope: 1
Endpoint___showWritePatient: 1
Endpoint___showReadPatient: 1
Endpoint___showWriteUser: 1
Endpoint___showReadUser: 1
Practitioner___showToPatientScope: 1
Practitioner___showToUserScope: 1
Practitioner___showWritePatient: 1
Practitioner___showReadPatient: 1
Practitioner___showWriteUser: 1
Practitioner___showReadUser: 1
DiagnosticOrder___showToPatientScope: 1
DiagnosticOrder___showToUserScope: 1
DiagnosticOrder___showWritePatient: 1
DiagnosticOrder___showReadPatient: 1
DiagnosticOrder___showWriteUser: 1
DiagnosticOrder___showReadUser: 1
MedicationDispense___showToPatientScope: 1
MedicationDispense___showToUserScope: 1
MedicationDispense___showWritePatient: 1
MedicationDispense___showReadPatient: 1
MedicationDispense___showWriteUser: 1
MedicationDispense___showReadUser: 1
Immunization___showToPatientScope: 1
Immunization___showToUserScope: 1
Immunization___showWritePatient: 1
Immunization___showReadPatient: 1
Immunization___showWriteUser: 1
Immunization___showReadUser: 1
ClaimResponse___showToPatientScope: 1
ClaimResponse___showToUserScope: 1
ClaimResponse___showWritePatient: 1
ClaimResponse___showReadPatient: 1
ClaimResponse___showWriteUser: 1
ClaimResponse___showReadUser: 1
Procedure___showToPatientScope: 1
Procedure___showToUserScope: 1
Procedure___showWritePatient: 1
Procedure___showReadPatient: 1
Procedure___showWriteUser: 1
Procedure___showReadUser: 1
Condition___showToPatientScope: 1
Condition___showToUserScope: 1
Condition___showWritePatient: 1
Condition___showReadPatient: 1
Condition___showWriteUser: 1
Condition___showReadUser: 1
MedicationAdministration___showToPatientScope: 1
MedicationAdministration___showToUserScope: 1
MedicationAdministration___showWritePatient: 1
MedicationAdministration___showReadPatient: 1
MedicationAdministration___showWriteUser: 1
MedicationAdministration___showReadUser: 1
MedicationStatement___showToPatientScope: 1
MedicationStatement___showToUserScope: 1
MedicationStatement___showWritePatient: 1
MedicationStatement___showReadPatient: 1
MedicationStatement___showWriteUser: 1
MedicationStatement___showReadUser: 1
EndPoint___showToPatientScope: 1
EndPoint___showToUserScope: 1
EndPoint___showWritePatient: 1
EndPoint___showReadPatient: 1
EndPoint___showWriteUser: 1
EndPoint___showReadUser: 1
BaseEndPoints___showToPatientScope: 1
BaseEndPoints___showToUserScope: 1
BaseEndPoints___showWritePatient: 1
BaseEndPoints___showReadPatient: 1
BaseEndPoints___showWriteUser: 1
BaseEndPoints___showReadUser: 1
Binary___showToPatientScope: 1
Binary___showToUserScope: 1
Binary___showWritePatient: 1
Binary___showReadPatient: 1
Binary___showWriteUser: 1
Binary___showReadUser: 1
Composition___showToPatientScope: 1
Composition___showToUserScope: 1
Composition___showWritePatient: 1
Composition___showReadPatient: 1
Composition___showWriteUser: 1
Composition___showReadUser: 1
BaseEndpoints___showToPatientScope: 1
BaseEndpoints___showToUserScope: 1
BaseEndpoints___showWritePatient: 1
BaseEndpoints___showReadPatient: 1
BaseEndpoints___showWriteUser: 1
BaseEndpoints___showReadUser: 1
_core:
  default_config_hash: mPsRQXoxekUx_Sks-4ASmYULWGWMdlAx7P-mAPSzN7o
CareTeam___showToPatientScope: 1
CareTeam___showToUserScope: 1
CareTeam___showWritePatient: 1
CareTeam___showReadPatient: 1
CareTeam___showWriteUser: 1
CareTeam___showReadUser: 1
Device___showToPatientScope: 1
Device___showToUserScope: 1
Device___showWritePatient: 1
Device___showReadPatient: 1
Device___showWriteUser: 1
Device___showReadUser: 1
Goal___showToPatientScope: 1
Goal___showToUserScope: 1
Goal___showWritePatient: 1
Goal___showReadPatient: 1
Goal___showWriteUser: 1
Goal___showReadUser: 1
Medication___showToPatientScope: 1
Medication___showToUserScope: 1
Medication___showWritePatient: 1
Medication___showReadPatient: 1
Medication___showWriteUser: 1
Medication___showReadUser: 1
Organization___showToPatientScope: 1
Organization___showToUserScope: 1
Organization___showWritePatient: 1
Organization___showReadPatient: 1
Organization___showWriteUser: 1
Organization___showReadUser: 1
PractitionerRole___showToPatientScope: 1
PractitionerRole___showToUserScope: 1
PractitionerRole___showWritePatient: 1
PractitionerRole___showReadPatient: 1
PractitionerRole___showWriteUser: 1
PractitionerRole___showReadUser: 1
Provenance___showToPatientScope: 1
Provenance___showToUserScope: 1
Provenance___showWritePatient: 1
Provenance___showReadPatient: 1
Provenance___showWriteUser: 1
Provenance___showReadUser: 1
RelatedPerson___showToPatientScope: 1
RelatedPerson___showToUserScope: 1
RelatedPerson___showWritePatient: 1
RelatedPerson___showReadPatient: 1
RelatedPerson___showWriteUser: 1
RelatedPerson___showReadUser: 1
