auth:
  social_auth_google:
    route: social_auth_google.redirect_to_google
    img_path: modules/contrib/social_auth_google/img/google_logo.svg
post_login: /user/my-apps
redirect_user_form: false
disable_admin_login: false
disabled_roles:
  healthcare_site_user: '0'
  administrator: '0'
  api_team: '0'
_core:
  default_config_hash: 1tS3jCuYxV3TXQ2cq320XarjdXWprvWK5bru8DCsIUY
