openapi: 3.0.1
info:
  title: HL7® FHIR® AllergyIntolerance resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: "Google Cloud Healthcare FHIR APIs - STU3"
paths:
  /AllergyIntolerance:
    get:
      tags:
        - AllergyIntolerance
      description: 'Returns AllergyIntolerances based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerances Search
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
    put:
      tags:
        - AllergyIntolerance
      description: 'The conditional update interaction is used to update an existing AllergyIntolerance based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance Conditional Update
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.write
    post:
      tags:
        - AllergyIntolerance
      description: 'Create a new AllergyIntolerance with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: Create AllergyIntolerance
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.write
    delete:
      tags:
        - AllergyIntolerance
      description: 'The conditional delete interaction allows a client to delete AllergyIntolerance/AllergyIntolerances  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.write
  '/AllergyIntolerance/{id}':
    get:
      tags:
        - AllergyIntolerance
      description: 'Returns details of AllergyIntolerance having id given in path.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: Read AllergyIntolerance
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
    put:
      tags:
        - AllergyIntolerance
      description: 'Update an existing AllergyIntolerance by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: Update AllergyIntolerance
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.write
    delete:
      tags:
        - AllergyIntolerance
      description: 'The delete interaction removes an existing AllergyIntolerance.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: Delete AllergyIntolerance
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.write
  '/AllergyIntolerance/{id}/_history':
    get:
      tags:
        - AllergyIntolerance
      description: 'It retrieves the history of a particular AllergyIntolerance identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance History
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
  /AllergyIntolerance/_history:
    get:
      tags:
        - AllergyIntolerance
      description: 'It retrieves the history of all resources of AllergyIntolerance.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerances History
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
  '/AllergyIntolerance/{id}/_history/{vid}':
    get:
      tags:
        - AllergyIntolerance
      description: 'This interaction preforms a version specific read of AllergyIntolerance resource.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance Version Read
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
  /AllergyIntolerance/$meta:
    get:
      tags:
        - AllergyIntolerance
      description: 'Retrieves a summary of the profiles, tags, and security labels for AllergyIntolerances.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerances Metadata
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
  '/AllergyIntolerance/{id}/$meta':
    get:
      tags:
        - AllergyIntolerance
      description: 'Retrieves a summary of the profiles, tags, and security labels for given AllergyIntolerance resource.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance Metadata
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
  '/AllergyIntolerance/{id}/_history/{vid}/$meta':
    get:
      tags:
        - AllergyIntolerance
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the AllergyIntolerance.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerance Version based Metadata
      security: 
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
  '/AllergyIntolerance/{id}/{type}':
    get:
      tags:
        - AllergyIntolerance
      description: 'Search the specified resource type in AllergyIntolerance compartment.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
  /AllergyIntolerance/_search:
    post:
      tags:
        - AllergyIntolerance
      description: 'This interaction searches a set of AllergyIntolerances based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: AllergyIntolerances Search using POST
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.read
  '/AllergyIntolerance/{id}/$meta-add':
    post:
      tags:
        - AllergyIntolerance
      description: 'Add a metadata info AllergyIntolerance with specified id.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: Add AllergyIntolerance metadata
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.write
  '/AllergyIntolerance/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - AllergyIntolerance
      description: 'Add metadata info to specified AllergyIntolerance resource.<p><a href = ''https://www.hl7.org/fhir/allergyintolerance.html''>FHIR documentation for AllergyIntolerance.</a></p>'
      operationId: Add AllergyIntolerance Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/AllergyIntolerance.write
components:
  securitySchemes:
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/AllergyIntolerance.read: Read permissions for AllergyIntolerance demographics.
            patient/AllergyIntolerance.write: Write permissions for AllergyIntolerance demographics.
