openapi: 3.0.1
info:
  title: HL7® FHIR® BaseEndPoint resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API docs are part of the FHIR® Specifications (v3.0.2: STU 3). The current version which supercedes this version is 4.0.1 (R4) This section contains API docs for the few commonly used STU3 resources. API docs for other resources can be added by API publishers on request.
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: Google Cloud Healthcare FHIR APIs - STU3
paths:
  /metadata:
    get:
      description: Retrieves the server's conformance statement that defines how it supports resources and operations.
      operationId: Conformance Statement
      parameters:
        - name: Authorization
          in: header
          description: 'Specify access token for API in the given format: Bearer [access_token].'
          schema:
            type: string
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: _format
          in: query
          description: Format of data to be returned.
          schema:
            type: string
      responses:
        '200':
          description: Conformance resource
          content: {}
        default:
          description: unexpected error
          content: {}
      security:
        - OAuthV2B2B: []
  /_history:
    get:
      description: It retrieves the history of all resources supported by the system.
      operationId: Resources History
      parameters:
        - name: _format
          in: query
          description: Format of data to be returned.
          schema:
            type: string
        - name: _count
          in: query
          description: The number of resources needed in a page.
          schema:
            type: integer
        - name: _since
          in: query
          description: Specify an instant to only include resource versions that were created at or after the given instant in time. An instant in time is known at least to the second and always includes a time zone.
          schema:
            type: string
        - name: Authorization
          in: header
          description: 'Specify access token for API in the given format: Bearer [access_token].'
          schema:
            type: string
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
      responses:
        '200':
          description: 'A Bundle with type set to history containing the specified version history, sorted with oldest versions last, and including deleted resources.'
          content: {}
        default:
          description: unexpected error
          content: {}
      security:
        - OAuthV2B2B: []
  /$meta:
    get:
      description: 'Retrieves a summary of the profiles, tags, and security labels used by the system.'
      operationId: Resources Metadata
      parameters:
        - name: _format
          in: query
          description: Format of data to be returned.
          schema:
            type: string
        - name: Authorization
          in: header
          description: 'Specify access token for API in the given format: Bearer [access_token].'
          schema:
            type: string
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
      responses:
        '200':
          description: 'Retrieves a summary of the profiles, tags, and security labels used by the system.'
          content: {}
        default:
          description: unexpected error
          content: {}
      security:
        - OAuthV2B2B: []
components:
  securitySchemes:
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/BaseEndPoint.read: Read permissions for BaseEndPoint demographics.
            patient/BaseEndPoint.write: Write permissions for BaseEndPoint demographics.
