openapi: 3.0.1
info:
  title: HL7® FHIR® Binary resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: Google Cloud Healthcare FHIR APIs - STU3
paths:
  /Binary:
    get:
      tags:
        - Binary
      security:
        - OAuthV2B2B:
            - patient/Binary.read
    put:
      tags:
        - Binary
      security:
        - OAuthV2B2B:
            - patient/Binary.read
    post:
      tags:
        - Binary
      description: 'Create a new Binary with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/binary.html''>FHIR documentation for Binary.</a></p>'
      operationId: Create Binary
      security:
        - OAuthV2B2B:
            - patient/Binary.write
    delete:
      tags:
        - Binary
      security:
        - OAuthV2B2B:
            - patient/Binary.read
  '/Binary/{id}':
    get:
      tags:
        - Binary
      security:
        - OAuthV2B2B:
            - patient/Binary.read
    put:
      tags:
        - Binary
      description: 'Update an existing Binary by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/binary.html''>FHIR documentation for Composition.</a></p>'
      operationId: Update Binary
      security:
        - OAuthV2B2B:
            - patient/Binary.write
    delete:
      tags:
        - Binary
      description: 'The delete interaction removes an existing Binary.<p><a href = ''https://www.hl7.org/fhir/binary.html''>FHIR documentation for Binary.</a></p>'
      operationId: Delete Binary
      security:
        - OAuthV2B2B:
            - patient/Binary.write
  '/Binary/{id}/_history':
    get:
      tags:
        - Binary
      description: 'It retrieves the history of a particular Binary identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/binary.html''>FHIR documentation for Binary.</a></p>'
      operationId: Binary History By ID
      security:
        - OAuthV2B2B:
            - patient/Binary.read
  /Binary/_history:
    get:
      tags:
        - Binary
      description: 'It retrieves the history of all resources of Binary.<p><a href = ''https://www.hl7.org/fhir/binary.html''>FHIR documentation for Binary.</a></p>'
      operationId: Composition History
      security:
        - OAuthV2B2B:
            - patient/Binary.read
  '/Binary/{id}/_history/{vid}':
    get:
      tags:
        - Binary
      description: 'This interaction preforms a version specific read of Binary resource.<p><a href = ''https://www.hl7.org/fhir/binary.html''>FHIR documentation for Binary.</a></p>'
      operationId: Binary Version Read
      security:
        - OAuthV2B2B:
            - patient/Binary.read
components:
  securitySchemes: 
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Binary.read: Read permissions for Binary demographics.
            patient/Binary.write: Write permissions for Binary demographics.
