openapi: 3.0.1
info:
  title: HL7® FHIR® CarePlan resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: "Google Cloud Healthcare FHIR APIs - STU3"
paths:
  /CarePlan:
    get:
      tags:
        - CarePlan
      description: 'Returns CarePlans based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlans Search
      security:
        - OAuthV2B2B:
          - patient/CarePlan.read
    put:
      tags:
        - CarePlan
      description: 'The conditional update interaction is used to update an existing CarePlan based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan Conditional Update
      security:
        - OAuthV2B2B:
          - patient/CarePlan.write
    post:
      tags:
        - CarePlan
      description: 'Create a new CarePlan with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: Create CarePlan
      security:
        - OAuthV2B2B:
          - patient/CarePlan.write
    delete:
      tags:
        - CarePlan
      description: 'The conditional delete interaction allows a client to delete CarePlan/CarePlans  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan Conditional Delete
      security:
        - OAuthV2B2B:
          - patient/CarePlan.write
  '/CarePlan/{id}':
    get:
      tags:
        - CarePlan
      description: 'Returns details of CarePlan having id given in path.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: Read CarePlan
      security:
        - OAuthV2B2B:
          - patient/CarePlan.read
    put:
      tags:
        - CarePlan
      description: 'Update an existing CarePlan by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: Update CarePlan
      security:
        - OAuthV2B2B:
          - patient/CarePlan.write
    delete:
      tags:
        - CarePlan
      description: 'The delete interaction removes an existing CarePlan.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: Delete CarePlan
      security:
        - OAuthV2B2B:
          - patient/CarePlan.write
  '/CarePlan/{id}/_history':
    get:
      tags:
        - CarePlan
      description: 'It retrieves the history of a particular CarePlan identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan History
      security:
        - OAuthV2B2B:
          - patient/CarePlan.read
  /CarePlan/_history:
    get:
      tags:
        - CarePlan
      description: 'It retrieves the history of all resources of CarePlan.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlans History
      security:
        - OAuthV2B2B:
          - patient/CarePlan.read
  '/CarePlan/{id}/_history/{vid}':
    get:
      tags:
        - CarePlan
      description: 'This interaction preforms a version specific read of CarePlan resource.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan Version Read
      security:
        - OAuthV2B2B:
          - patient/CarePlan.read
  /CarePlan/$meta:
    get:
      tags:
        - CarePlan
      description: 'Retrieves a summary of the profiles, tags, and security labels for CarePlans.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlans Metadata
      security:
        - OAuthV2B2B:
          - patient/CarePlan.read
  '/CarePlan/{id}/$meta':
    get:
      tags:
        - CarePlan
      description: 'Retrieves a summary of the profiles, tags, and security labels for given CarePlan resource.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan Metadata
      security:
        - OAuthV2B2B:
          - patient/CarePlan.read
  '/CarePlan/{id}/_history/{vid}/$meta':
    get:
      tags:
        - CarePlan
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the CarePlan.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlan Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/CarePlan.read
  '/CarePlan/{id}/{type}':
    get:
      tags:
        - CarePlan
      description: 'Search the specified resource type in CarePlan compartment.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
          - patient/CarePlan.read
  /CarePlan/_search:
    post:
      tags:
        - CarePlan
      description: 'This interaction searches a set of CarePlans based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: CarePlans Search using POST
      security:
        - OAuthV2B2B:
          - patient/CarePlan.write
  '/CarePlan/{id}/$meta-add':
    post:
      tags:
        - CarePlan
      description: 'Add a metadata info CarePlan with specified id.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: Add CarePlan metadata
      security:
        - OAuthV2B2B:
          - patient/CarePlan.write
  '/CarePlan/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - CarePlan
      description: 'Add metadata info to specified CarePlan resource.<p><a href = ''https://www.hl7.org/fhir/careplan.html''>FHIR documentation for CarePlan.</a></p>'
      operationId: Add CarePlan Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/CarePlan.write
components:
  securitySchemes: 
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/CarePlan.read: Read permissions for CarePlan demographics.
            patient/CarePlan.write: Write permissions for CarePlan demographics.
          
