openapi: 3.0.1
info:
  title: HL7® FHIR® ClaimResponse resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: "Google Cloud Healthcare FHIR APIs - STU3"
paths:
  /ClaimResponse:
    get:
      tags:
        - ClaimResponse
      description: 'Returns ClaimResponse based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Search
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
    put:
      tags:
        - ClaimResponse
      description: 'The conditional update interaction is used to update an existing ClaimResponse based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Conditional Update
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.write
    post:
      tags:
        - ClaimResponse
      description: 'Create a new ClaimResponse with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: Create ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.write
    delete:
      tags:
        - ClaimResponse
      description: 'The conditional delete interaction allows a client to delete ClaimResponse/ClaimResponse  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.write
  '/ClaimResponse/{id}':
    get:
      tags:
        - ClaimResponse
      description: 'Returns details of ClaimResponse having id given in path.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: Read ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
    put:
      tags:
        - ClaimResponse
      description: 'Update an existing ClaimResponse by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: Update ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.write
    delete:
      tags:
        - ClaimResponse
      description: 'The delete interaction removes an existing ClaimResponse.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: Delete ClaimResponse
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.write
  '/ClaimResponse/{id}/_history':
    get:
      tags:
        - ClaimResponse
      description: 'It retrieves the history of a particular ClaimResponse identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse History
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
  /ClaimResponse/_history:
    get:
      tags:
        - ClaimResponse
      description: 'It retrieves the history of all resources of ClaimResponse.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponses History
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
  '/ClaimResponse/{id}/_history/{vid}':
    get:
      tags:
        - ClaimResponse
      description: 'This interaction preforms a version specific read of ClaimResponse resource.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Version Read
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
  /ClaimResponse/$meta:
    get:
      tags:
        - ClaimResponse
      description: 'Retrieves a summary of the profiles, tags, and security labels for ClaimResponse.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
  '/ClaimResponse/{id}/$meta':
    get:
      tags:
        - ClaimResponse
      description: 'Retrieves a summary of the profiles, tags, and security labels for given ClaimResponse resource.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponses Metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
  '/ClaimResponse/{id}/_history/{vid}/$meta':
    get:
      tags:
        - ClaimResponse
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the ClaimResponse.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
  '/ClaimResponse/{id}/{type}':
    get:
      tags:
        - ClaimResponse
      description: 'Search the specified resource type in ClaimResponse compartment.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
  /ClaimResponse/_search:
    post:
      tags:
        - ClaimResponse
      description: 'This interaction searches a set of ClaimResponse based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: ClaimResponse Search using POST
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.read
  '/ClaimResponse/{id}/$meta-add':
    post:
      tags:
        - ClaimResponse
      description: 'Add a metadata info ClaimResponse with specified id.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: Add ClaimResponse metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.write
  '/ClaimResponse/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - ClaimResponse
      description: 'Add metadata info to specified ClaimResponse resource.<p><a href = ''https://www.hl7.org/fhir/claimresponse.html''>FHIR documentation for ClaimResponse.</a></p>'
      operationId: Add ClaimResponse Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/ClaimResponse.write
components:
  securitySchemes: 
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/ClaimResponse.read: Read permissions for ClaimResponse demographics.
            patient/ClaimResponse.write: Write permissions for ClaimResponse demographics.
