openapi: 3.0.1
info:
  title: HL7® FHIR® Condition resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: "Google Cloud Healthcare FHIR APIs - STU3"
paths:
  /Condition:
    get:
      tags:
        - Condition
      description: 'Returns Conditions based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Conditions Search
      security:
        - OAuthV2B2B:
            - patient/Condition.read
    put:
      tags:
        - Condition
      description: 'The conditional update interaction is used to update an existing Condition based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition Conditional Update
      security:
        - OAuthV2B2B:
            - patient/Condition.write
    post:
      tags:
        - Condition
      description: 'Create a new Condition with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Create Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.write
    delete:
      tags:
        - Condition
      description: 'The conditional delete interaction allows a client to delete Condition/Conditions  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/Condition.write
  '/Condition/{id}':
    get:
      tags:
        - Condition
      description: 'Returns details of Condition having id given in path.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Read Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.read
    put:
      tags:
        - Condition
      description: 'Update an existing Condition by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Update Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.write
    delete:
      tags:
        - Condition
      description: 'The delete interaction removes an existing Condition.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Delete Condition
      security:
        - OAuthV2B2B:
            - patient/Condition.write
  '/Condition/{id}/_history':
    get:
      tags:
        - Condition
      description: 'It retrieves the history of a particular Condition identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition History
      security:
        - OAuthV2B2B:
            - patient/Condition.read
  /Condition/_history:
    get:
      tags:
        - Condition
      description: 'It retrieves the history of all resources of Condition.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Conditions History
      security:
        - OAuthV2B2B:
            - patient/Condition.read
  '/Condition/{id}/_history/{vid}':
    get:
      tags:
        - Condition
      description: 'This interaction preforms a version specific read of Condition resource.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition Version Read
      security:
        - OAuthV2B2B:
            - patient/Condition.read
  /Condition/$meta:
    get:
      tags:
        - Condition
      description: 'Retrieves a summary of the profiles, tags, and security labels for Conditions.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Conditions Metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.read
  '/Condition/{id}/$meta':
    get:
      tags:
        - Condition
      description: 'Retrieves a summary of the profiles, tags, and security labels for given Condition resource.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition Metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.read
  '/Condition/{id}/_history/{vid}/$meta':
    get:
      tags:
        - Condition
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the Condition.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Condition Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.read
  '/Condition/{id}/{type}':
    get:
      tags:
        - Condition
      description: 'Search the specified resource type in Condition compartment.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/Condition.read
  /Condition/_search:
    post:
      tags:
        - Condition
      description: 'This interaction searches a set of Conditions based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Conditions Search using POST
      security:
        - OAuthV2B2B:
            - patient/Condition.read
  '/Condition/{id}/$meta-add':
    post:
      tags:
        - Condition
      description: 'Add a metadata info Condition with specified id.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Add Condition metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.write
  '/Condition/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - Condition
      description: 'Add metadata info to specified Condition resource.<p><a href = ''https://www.hl7.org/fhir/condition.html''>FHIR documentation for Condition.</a></p>'
      operationId: Add Condition Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Condition.write
components:
  securitySchemes:

    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Condition.read: Read permissions for Condition demographics.
            patient/Condition.write: Write permissions for Condition demographics.
