openapi: 3.0.1
info:
  title: HL7® FHIR® Coverage resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: "Google Cloud Healthcare FHIR APIs - STU3"
paths:
  /Coverage:
    get:
      tags:
        - Coverage
      description: 'Returns Coverages based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverages Search
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
    put:
      tags:
        - Coverage
      description: 'The conditional update interaction is used to update an existing Coverage based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverage Conditional Update
      security:
        - OAuthV2B2B:
            - patient/Coverage.write
    post:
      tags:
        - Coverage
      description: 'Create a new Coverage with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Create Coverage
      security:
        - OAuthV2B2B:
            - patient/Coverage.write
    delete:
      tags:
        - Coverage
      description: 'The conditional delete interaction allows a client to delete Coverage/Coverages  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverage Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/Coverage.write
  '/Coverage/{id}':
    get:
      tags:
        - Coverage
      description: 'Returns details of Coverage having id given in path.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Read Coverage
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
    put:
      tags:
        - Coverage
      description: 'Update an existing Coverage by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Update Coverage
      security:
        - OAuthV2B2B:
            - patient/Coverage.write
    delete:
      tags:
        - Coverage
      description: 'The delete interaction removes an existing Coverage.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Delete Coverage
      security:
        - OAuthV2B2B:
            - patient/Coverage.write
  '/Coverage/{id}/_history':
    get:
      tags:
        - Coverage
      description: 'It retrieves the history of a particular Coverage identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverage History
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
  /Coverage/_history:
    get:
      tags:
        - Coverage
      description: 'It retrieves the history of all resources of Coverage.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverages History
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
  '/Coverage/{id}/_history/{vid}':
    get:
      tags:
        - Coverage
      description: 'This interaction preforms a version specific read of Coverage resource.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverage Version Read
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
  /Coverage/$meta:
    get:
      tags:
        - Coverage
      description: 'Retrieves a summary of the profiles, tags, and security labels for Coverages.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverages Metadata
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
  '/Coverage/{id}/$meta':
    get:
      tags:
        - Coverage
      description: 'Retrieves a summary of the profiles, tags, and security labels for given Coverage resource.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverage Metadata
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
  '/Coverage/{id}/_history/{vid}/$meta':
    get:
      tags:
        - Coverage
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the Coverage.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverage Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
  '/Coverage/{id}/{type}':
    get:
      tags:
        - Coverage
      description: 'Search the specified resource type in Coverage compartment.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
  /Coverage/_search:
    post:
      tags:
        - Coverage
      description: 'This interaction searches a set of Coverages based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Coverages Search using POST
      security:
        - OAuthV2B2B:
            - patient/Coverage.read
  '/Coverage/{id}/$meta-add':
    post:
      tags:
        - Coverage
      description: 'Add a metadata info Coverage with specified id.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Add Coverage metadata
      security:
        - OAuthV2B2B:
            - patient/Coverage.write
  '/Coverage/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - Coverage
      description: 'Add metadata info to specified Coverage resource.<p><a href = ''https://www.hl7.org/fhir/coverage.html''>FHIR documentation for Coverage.</a></p>'
      operationId: Add Coverage Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Coverage.write
components:
  securitySchemes: 
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Coverage.read: Read permissions for Coverage demographics.
            patient/Coverage.write: Write permissions for Coverage demographics.
