openapi: 3.0.1
info:
  title: HL7® FHIR® DocumentReference resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: "Google Cloud Healthcare FHIR APIs - STU3"
paths:
  /DocumentReference:
    get:
      tags:
        - DocumentReference
      description: 'Returns DocumentReferences based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReferences Search
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
    put:
      tags:
        - DocumentReference
      description: 'The conditional update interaction is used to update an existing DocumentReference based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReference Conditional Update
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.write
    post:
      tags:
        - DocumentReference
      description: 'Create a new DocumentReference with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: Create DocumentReference
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.write
    delete:
      tags:
        - DocumentReference
      description: 'The conditional delete interaction allows a client to delete DocumentReference/DocumentReferences  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReference Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.write
  '/DocumentReference/{id}':
    get:
      tags:
        - DocumentReference
      description: 'Returns details of DocumentReference having id given in path.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: Read DocumentReference
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.write
    put:
      tags:
        - DocumentReference
      description: 'Update an existing DocumentReference by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: Update DocumentReference
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
    delete:
      tags:
        - DocumentReference
      description: 'The delete interaction removes an existing DocumentReference.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: Delete DocumentReference
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.write
  '/DocumentReference/{id}/_history':
    get:
      tags:
        - DocumentReference
      description: 'It retrieves the history of a particular DocumentReference identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReference History
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
  /DocumentReference/_history:
    get:
      tags:
        - DocumentReference
      description: 'It retrieves the history of all resources of DocumentReference.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReferences History
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
  '/DocumentReference/{id}/_history/{vid}':
    get:
      tags:
        - DocumentReference
      description: 'This interaction preforms a version specific read of DocumentReference resource.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReference Version Read
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
  /DocumentReference/$meta:
    get:
      tags:
        - DocumentReference
      description: 'Retrieves a summary of the profiles, tags, and security labels for DocumentReferences.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReferences Metadata
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
  '/DocumentReference/{id}/$meta':
    get:
      tags:
        - DocumentReference
      description: 'Retrieves a summary of the profiles, tags, and security labels for given DocumentReference resource.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReference Metadata
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
  '/DocumentReference/{id}/_history/{vid}/$meta':
    get:
      tags:
        - DocumentReference
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the DocumentReference.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReference Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
  '/DocumentReference/{id}/{type}':
    get:
      tags:
        - DocumentReference
      description: 'Search the specified resource type in DocumentReference compartment.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
  /DocumentReference/_search:
    post:
      tags:
        - DocumentReference
      description: 'This interaction searches a set of DocumentReferences based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: DocumentReferences Search using POST
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.read
  '/DocumentReference/{id}/$meta-add':
    post:
      tags:
        - DocumentReference
      description: 'Add a metadata info DocumentReference with specified id.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: Add DocumentReference metadata
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.write
  '/DocumentReference/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - DocumentReference
      description: 'Add metadata info to specified DocumentReference resource.<p><a href = ''https://www.hl7.org/fhir/documentreference.html''>FHIR documentation for DocumentReference.</a></p>'
      operationId: Add DocumentReference Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/DocumentReference.write
components:
  securitySchemes: 
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/DocumentReference.read: Read permissions for DocumentReference demographics.
            patient/DocumentReference.write: Write permissions for DocumentReference demographics.
