openapi: 3.0.1
info:
  title: HL7® FHIR® Encounter resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: "Google Cloud Healthcare FHIR APIs - STU3"
paths:
  /Encounter:
    get:
      tags:
        - Encounter
      description: 'Returns Encounters based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounters Search
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
    put:
      tags:
        - Encounter
      description: 'The conditional update interaction is used to update an existing Encounter based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounter Conditional Update
      security:
        - OAuthV2B2B:
          - patient/Encounter.write
    post:
      tags:
        - Encounter
      description: 'Create a new Encounter with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Create Encounter
      security:
        - OAuthV2B2B:
          - patient/Encounter.write
    delete:
      tags:
        - Encounter
      description: 'The conditional delete interaction allows a client to delete Encounter/Encounters  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounter Conditional Delete
      security:
        - OAuthV2B2B:
          - patient/Encounter.write
  '/Encounter/{id}':
    get:
      tags:
        - Encounter
      description: 'Returns details of Encounter having id given in path.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Read Encounter
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
    put:
      tags:
        - Encounter
      description: 'Update an existing Encounter by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Update Encounter
      security:
        - OAuthV2B2B:
          - patient/Encounter.write
    delete:
      tags:
        - Encounter
      description: 'The delete interaction removes an existing Encounter.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Delete Encounter
      security:
        - OAuthV2B2B:
          - patient/Encounter.write
  '/Encounter/{id}/_history':
    get:
      tags:
        - Encounter
      description: 'It retrieves the history of a particular Encounter identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounter History
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
  /Encounter/_history:
    get:
      tags:
        - Encounter
      description: 'It retrieves the history of all resources of Encounter.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounters History
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
  '/Encounter/{id}/_history/{vid}':
    get:
      tags:
        - Encounter
      description: 'This interaction preforms a version specific read of Encounter resource.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounter Version Read
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
  /Encounter/$meta:
    get:
      tags:
        - Encounter
      description: 'Retrieves a summary of the profiles, tags, and security labels for Encounters.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounters Metadata
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
  '/Encounter/{id}/$meta':
    get:
      tags:
        - Encounter
      description: 'Retrieves a summary of the profiles, tags, and security labels for given Encounter resource.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounter Metadata
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
  '/Encounter/{id}/_history/{vid}/$meta':
    get:
      tags:
        - Encounter
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the Encounter.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounter Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
  '/Encounter/{id}/{type}':
    get:
      tags:
        - Encounter
      description: 'Search the specified resource type in Encounter compartment.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
  /Encounter/_search:
    post:
      tags:
        - Encounter
      description: 'This interaction searches a set of Encounters based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Encounters Search using POST
      security:
        - OAuthV2B2B:
          - patient/Encounter.write
  '/Encounter/{id}/$meta-add':
    post:
      tags:
        - Encounter
      description: 'Add a metadata info Encounter with specified id.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Add Encounter metadata
      security:
        - OAuthV2B2B:
          - patient/Encounter.write
  '/Encounter/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - Encounter
      description: 'Add metadata info to specified Encounter resource.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Add Encounter Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/Encounter.write
  '/Encounter/{id}/$everything':
    get:
      tags:
        - Encounter
      description: 'Returns all the information related to a specific Encounter resource.<p><a href = ''https://www.hl7.org/fhir/encounter.html''>FHIR documentation for Encounter.</a></p>'
      operationId: Fetch Encounter Record
      security:
        - OAuthV2B2B:
          - patient/Encounter.read
components:
  securitySchemes: 
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Encounter.read: Read permissions for Encounter demographics.
            patient/Encounter.write: Write permissions for Encounter demographics.
