openapi: 3.0.1
info:
  title: HL7® FHIR® Endpoint resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: Google Cloud Healthcare FHIR APIs - STU3
paths:
  /Endpoint:
    get:
      tags:
        - Endpoint
      security:
        - OAuthV2B2B:
          - patient/ClaimResponse
    put:
      tags:
        - Endpoint
      security:
        - OAuthV2B2B:
          - patient/ClaimResponse
    post:
      tags:
        - Endpoint
      description: 'Create a new Endpoint with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/endpoint.html''>FHIR documentation for Endpoint.</a></p>'
      operationId: Create Endpoint
      security:
        - OAuthV2B2B:
          - patient/Endpoint.write
    delete:
      tags:
        - Endpoint
      security:
        - OAuthV2B2B:
          - patient/ClaimResponse
  '/Endpoint/{id}':
    get:
      tags:
        - Endpoint
      security:
        - OAuthV2B2B:
          - patient/ClaimResponse
    put:
      tags:
        - Endpoint
      security:
        - OAuthV2B2B:
          - patient/ClaimResponse
    delete:
      tags:
        - Endpoint
      security:
        - OAuthV2B2B:
          - patient/ClaimResponse
  '/Endpoint/{id}/_history':
    get:
      tags:
        - Endpoint
      description: 'It retrieves the history of a particular Endpoint identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/endpoint.html''>FHIR documentation for Endpoint.</a></p>'
      operationId: Endpoint History By ID
      security:
        - OAuthV2B2B:
          - patient/ClaimResponse
  /Endpoint/_history:
    get:
      tags:
        - Endpoint
      description: 'It retrieves the history of all resources of Endpoint.<p><a href = ''https://www.hl7.org/fhir/endpoint.html''>FHIR documentation for Endpoint.</a></p>'
      operationId: Composition History
      security:
        - OAuthV2B2B:
          - patient/ClaimResponse
  '/Endpoint/{id}/_history/{vid}':
    get:
      tags:
        - Endpoint
      description: 'This interaction preforms a version specific read of Endpoint resource.<p><a href = ''https://www.hl7.org/fhir/endpoint.html''>FHIR documentation for Endpoint.</a></p>'
      operationId: Endpoint Version Read
      security:
        - OAuthV2B2B:
          - patient/ClaimResponse
components:
  securitySchemes: 
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Endpoint.read: Read permissions for Endpoint demographics.
            patient/Endpoint.write: Write permissions for Endpoint demographics.
