openapi: 3.0.1
info:
  title: HL7® FHIR® MedicationStatement resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
paths:
  /MedicationStatement:
    get:
      tags:
        - MedicationStatement
      description: 'Returns MedicationStatement based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatement Search
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.read
    put:
      tags:
        - MedicationStatement
      description: 'The conditional update interaction is used to update an existing MedicationStatement based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatement Conditional Update
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.write
    post:
      tags:
        - MedicationStatement
      description: 'Create a new MedicationStatement with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: Create MedicationStatement
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.write
    delete:
      tags:
        - MedicationStatement
      description: 'The conditional delete interaction allows a client to delete MedicationStatement/MedicationStatement  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatement Conditional Delete
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.write
  '/MedicationStatement/{id}':
    get:
      tags:
        - MedicationStatement
      description: 'Returns details of MedicationStatement having id given in path.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: Read MedicationStatement
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.read
    put:
      tags:
        - MedicationStatement
      description: 'Update an existing MedicationStatement by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: Update MedicationStatement
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.write
    delete:
      tags:
        - MedicationStatement
      description: 'The delete interaction removes an existing MedicationStatement.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: Delete MedicationStatement
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.write
  '/MedicationStatement/{id}/_history':
    get:
      tags:
        - MedicationStatement
      description: 'It retrieves the history of a particular MedicationStatement identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatement History
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.read
  /MedicationStatement/_history:
    get:
      tags:
        - MedicationStatement
      description: 'It retrieves the history of all resources of MedicationStatement.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatementHistory
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.read
  '/MedicationStatement/{id}/_history/{vid}':
    get:
      tags:
        - MedicationStatement
      description: 'This interaction preforms a version specific read of MedicationStatement resource.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatement Version Read
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.read
  /MedicationStatement/$meta:
    get:
      tags:
        - MedicationStatement
      description: 'Retrieves a summary of the profiles, tags, and security labels for MedicationStatement.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatement Metadata
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.read
  '/MedicationStatement/{id}/$meta':
    get:
      tags:
        - MedicationStatement
      description: 'Retrieves a summary of the profiles, tags, and security labels for given MedicationStatement resource.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatementMetadata
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.read
  '/MedicationStatement/{id}/_history/{vid}/$meta':
    get:
      tags:
        - MedicationStatement
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the MedicationStatement.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatement Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.read
  '/MedicationStatement/{id}/{type}':
    get:
      tags:
        - MedicationStatement
      description: 'Search the specified resource type in MedicationStatement compartment.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.read
  /MedicationStatement/_search:
    post:
      tags:
        - MedicationStatement
      description: 'This interaction searches a set of MedicationStatement based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: MedicationStatement Search using POST
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.write
  '/MedicationStatement/{id}/$meta-add':
    post:
      tags:
        - MedicationStatement
      description: 'Add a metadata info MedicationStatement with specified id.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: Add MedicationStatement metadata
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.write
  '/MedicationStatement/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - MedicationStatement
      description: 'Add metadata info to specified MedicationStatement resource.<p><a href = ''https://www.hl7.org/fhir/medicationstatement.html''>FHIR documentation for MedicationStatement.</a></p>'
      operationId: Add MedicationStatement Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/MedicationStatement.write
components:
  securitySchemes:
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/MedicationStatement.read: Read permissions for MedicationStatement demographics.
            patient/MedicationStatement.write: Write permissions for MedicationStatement demographics.