openapi: 3.0.1
info:
  title: HL7® FHIR® MedicationAdministration resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
paths:
  /MedicationAdministration:
    get:
      tags:
        - MedicationAdministration
      description: 'Returns MedicationAdministrations based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministrations Search
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.read
    put:
      tags:
        - MedicationAdministration
      description: 'The conditional update interaction is used to update an existing MedicationAdministration based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministration Conditional Update
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.write
    post:
      tags:
        - MedicationAdministration
      description: 'Create a new MedicationAdministration with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: Create MedicationAdministration
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.write
    delete:
      tags:
        - MedicationAdministration
      description: 'The conditional delete interaction allows a client to delete MedicationAdministration/MedicationAdministrations  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministration Conditional Delete
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.write
  '/MedicationAdministration/{id}':
    get:
      tags:
        - MedicationAdministration
      description: 'Returns details of MedicationAdministration having id given in path.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: Read MedicationAdministration
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.read
    put:
      tags:
        - MedicationAdministration
      description: 'Update an existing MedicationAdministration by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: Update MedicationAdministration
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.write
    delete:
      tags:
        - MedicationAdministration
      description: 'The delete interaction removes an existing MedicationAdministration.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: Delete MedicationAdministration
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.write
  '/MedicationAdministration/{id}/_history':
    get:
      tags:
        - MedicationAdministration
      description: 'It retrieves the history of a particular MedicationAdministration identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministration History
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.read
  /MedicationAdministration/_history:
    get:
      tags:
        - MedicationAdministration
      description: 'It retrieves the history of all resources of MedicationAdministration.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministrations History
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.read
  '/MedicationAdministration/{id}/_history/{vid}':
    get:
      tags:
        - MedicationAdministration
      description: 'This interaction preforms a version specific read of MedicationAdministration resource.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministration Version Read
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.read
  /MedicationAdministration/$meta:
    get:
      tags:
        - MedicationAdministration
      description: 'Retrieves a summary of the profiles, tags, and security labels for MedicationAdministrations.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministrations Metadata
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.read
  '/MedicationAdministration/{id}/$meta':
    get:
      tags:
        - MedicationAdministration
      description: 'Retrieves a summary of the profiles, tags, and security labels for given MedicationAdministration resource.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministration Metadata
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.read
  '/MedicationAdministration/{id}/_history/{vid}/$meta':
    get:
      tags:
        - MedicationAdministration
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the MedicationAdministration.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministration Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.read
  '/MedicationAdministration/{id}/{type}':
    get:
      tags:
        - MedicationAdministration
      description: 'Search the specified resource type in MedicationAdministration compartment.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.read
  /MedicationAdministration/_search:
    post:
      tags:
        - MedicationAdministration
      description: 'This interaction searches a set of MedicationAdministrations based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: MedicationAdministrations Search using POST
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.write
  '/MedicationAdministration/{id}/$meta-add':
    post:
      tags:
        - MedicationAdministration
      description: 'Add a metadata info MedicationAdministration with specified id.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: Add MedicationAdministration metadata
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.write
  '/MedicationAdministration/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - MedicationAdministration
      description: 'Add metadata info to specified MedicationAdministration resource.<p><a href = ''https://www.hl7.org/fhir/medicationadministration.html''>FHIR documentation for MedicationAdministration.</a></p>'
      operationId: Add MedicationAdministration Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/MedicationAdministration.write
components:
  securitySchemes:
    
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/MedicationAdministration.read: Read permissions for MedicationAdministration demographics.
            patient/MedicationAdministration.write: Write permissions for MedicationAdministration demographics.
