openapi: 3.0.1
info:
  title: HL7® FHIR® MedicationDispense resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: "Google Cloud Healthcare FHIR APIs - STU3"
paths:
  /MedicationDispense:
    get:
      tags:
        - MedicationDispense
      description: 'Returns MedicationDispenses based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispenses Search
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
    put:
      tags:
        - MedicationDispense
      description: 'The conditional update interaction is used to update an existing MedicationDispense based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispense Conditional Update
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.write
    post:
      tags:
        - MedicationDispense
      description: 'Create a new MedicationDispense with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: Create MedicationDispense
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.write
    delete:
      tags:
        - MedicationDispense
      description: 'The conditional delete interaction allows a client to delete MedicationDispense/MedicationDispenses  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispense Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.write
  '/MedicationDispense/{id}':
    get:
      tags:
        - MedicationDispense
      description: 'Returns details of MedicationDispense having id given in path.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: Read MedicationDispense
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
    put:
      tags:
        - MedicationDispense
      description: 'Update an existing MedicationDispense by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: Update MedicationDispense
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.write
    delete:
      tags:
        - MedicationDispense
      description: 'The delete interaction removes an existing MedicationDispense.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: Delete MedicationDispense
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.write
  '/MedicationDispense/{id}/_history':
    get:
      tags:
        - MedicationDispense
      description: 'It retrieves the history of a particular MedicationDispense identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispense History
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
  /MedicationDispense/_history:
    get:
      tags:
        - MedicationDispense
      description: 'It retrieves the history of all resources of MedicationDispense.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispenses History
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
  '/MedicationDispense/{id}/_history/{vid}':
    get:
      tags:
        - MedicationDispense
      description: 'This interaction preforms a version specific read of MedicationDispense resource.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispense Version Read
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
  /MedicationDispense/$meta:
    get:
      tags:
        - MedicationDispense
      description: 'Retrieves a summary of the profiles, tags, and security labels for MedicationDispenses.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispenses Metadata
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
  '/MedicationDispense/{id}/$meta':
    get:
      tags:
        - MedicationDispense
      description: 'Retrieves a summary of the profiles, tags, and security labels for given MedicationDispense resource.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispense Metadata
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
  '/MedicationDispense/{id}/_history/{vid}/$meta':
    get:
      tags:
        - MedicationDispense
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the MedicationDispense.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispense Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
  '/MedicationDispense/{id}/{type}':
    get:
      tags:
        - MedicationDispense
      description: 'Search the specified resource type in MedicationDispense compartment.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
  /MedicationDispense/_search:
    post:
      tags:
        - MedicationDispense
      description: 'This interaction searches a set of MedicationDispenses based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: MedicationDispenses Search using POST
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.read
  '/MedicationDispense/{id}/$meta-add':
    post:
      tags:
        - MedicationDispense
      description: 'Add a metadata info MedicationDispense with specified id.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: Add MedicationDispense metadata
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.write
  '/MedicationDispense/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - MedicationDispense
      description: 'Add metadata info to specified MedicationDispense resource.<p><a href = ''https://www.hl7.org/fhir/medicationdispense.html''>FHIR documentation for MedicationDispense.</a></p>'
      operationId: Add MedicationDispense Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/MedicationDispense.write
components:
  securitySchemes: 
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/MedicationDispense.read: Read permissions for MedicationDispense demographics.
            patient/MedicationDispense.write: Write permissions for MedicationDispense demographics.
