openapi: 3.0.1
info:
  title: HL7® FHIR® Observation resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
paths:
  /Observation:
    get:
      tags:
        - Observation
      description: 'Returns Observations based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observations Search
      security:
        - OAuthV2B2B:
          - patient/Observation.read
    put:
      tags:
        - Observation
      description: 'The conditional update interaction is used to update an existing Observation based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observation Conditional Update
      security:
        - OAuthV2B2B:
          - patient/Observation.write
    post:
      tags:
        - Observation
      description: 'Create a new Observation with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Create Observation
      security:
        - OAuthV2B2B:
          - patient/Observation.write
    delete:
      tags:
        - Observation
      description: 'The conditional delete interaction allows a client to delete Observation/Observations  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observation Conditional Delete
      security:
        - OAuthV2B2B:
          - patient/Observation.write
  '/Observation/{id}':
    get:
      tags:
        - Observation
      description: 'Returns details of Observation having id given in path.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Read Observation
      security:
        - OAuthV2B2B:
          - patient/Observation.read
    put:
      tags:
        - Observation
      description: 'Update an existing Observation by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Update Observation
      security:
        - OAuthV2B2B:
          - patient/Observation.write
    delete:
      tags:
        - Observation
      description: 'The delete interaction removes an existing Observation.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Delete Observation
      security:
        - OAuthV2B2B:
          - patient/Observation.write
  '/Observation/{id}/_history':
    get:
      tags:
        - Observation
      description: 'It retrieves the history of a particular Observation identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observation History
      security:
        - OAuthV2B2B:
          - patient/Observation.read
  /Observation/_history:
    get:
      tags:
        - Observation
      description: 'It retrieves the history of all resources of Observation.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observations History
      security:
        - OAuthV2B2B:
          - patient/Observation.read
  '/Observation/{id}/_history/{vid}':
    get:
      tags:
        - Observation
      description: 'This interaction preforms a version specific read of Observation resource.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observation Version Read
      security:
        - OAuthV2B2B:
          - patient/Observation.read
  /Observation/$meta:
    get:
      tags:
        - Observation
      description: 'Retrieves a summary of the profiles, tags, and security labels for Observations.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observations Metadata
      security:
        - OAuthV2B2B:
          - patient/Observation.read
  '/Observation/{id}/$meta':
    get:
      tags:
        - Observation
      description: 'Retrieves a summary of the profiles, tags, and security labels for given Observation resource.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observation Metadata
      security:
        - OAuthV2B2B:
          - patient/Observation.read
  '/Observation/{id}/_history/{vid}/$meta':
    get:
      tags:
        - Observation
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the Observation.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observation Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/Observation.read
  '/Observation/{id}/{type}':
    get:
      tags:
        - Observation
      description: 'Search the specified resource type in Observation compartment.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
          - patient/Observation.read
  /Observation/_search:
    post:
      tags:
        - Observation
      description: 'This interaction searches a set of Observations based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Observations Search using POST
      security:
        - OAuthV2B2B:
          - patient/Observation.write
  '/Observation/{id}/$meta-add':
    post:
      tags:
        - Observation
      description: 'Add a metadata info Observation with specified id.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Add Observation metadata
      security:
        - OAuthV2B2B:
          - patient/Observation.write
  '/Observation/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - Observation
      description: 'Add metadata info to specified Observation resource.<p><a href = ''https://www.hl7.org/fhir/observation.html''>FHIR documentation for Observation.</a></p>'
      operationId: Add Observation Version based Metadata
      security:
        - OAuthV2B2B:
          - patient/Observation.write
components:
  securitySchemes: 
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Observation.read: Read permissions for Observation demographics.
            patient/Observation.write: Write permissions for Observation demographics.
