openapi: 3.0.1
info:
  title: HL7® FHIR® Procedure resource API documentation
  description: |
    Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced "Fire") defines a set of "Resources" that represent granular clinical concepts. The resources can be managed in isolation, or aggregated into complex documents. Technically, FHIR® is designed for the web; the resources are based on simple JSON structures, with an http-based RESTful protocol where each resource has predictable URL. Where possible, open internet standards are used for data representation. The FHIR® STU3 API doc[...]
servers:
  - url: 'https://org-env.apigee.net/v1/ghc/stu3'
    description: "Google Cloud Healthcare FHIR APIs - STU3"
paths:
  /Procedure:
    get:
      tags:
        - Procedure
      description: 'Returns Procedures based on filter criteria OR Provides provision for pagination (stateid, page, page_size, _pretty & _bundletype are query parameters used for Paging).<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedures Search
      security: 
        - OAuthV2B2B:
            - patient/Procedure.read
    put:
      tags:
        - Procedure
      description: 'The conditional update interaction is used to update an existing Procedure based on some identification criteria, rather than by logical id.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedure Conditional Update
      security:
        - OAuthV2B2B:
            - patient/Procedure.write
    post:
      tags:
        - Procedure
      description: 'Create a new Procedure with a server assigned id.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Create Procedure
      security:
        - OAuthV2B2B:
            - patient/Procedure.write
    delete:
      tags:
        - Procedure
      description: 'The conditional delete interaction allows a client to delete Procedure/Procedures  based on some selection criteria, rather than by a specific logical id.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedure Conditional Delete
      security:
        - OAuthV2B2B:
            - patient/Procedure.write
  '/Procedure/{id}':
    get:
      tags:
        - Procedure
      description: 'Returns details of Procedure having id given in path.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Read Procedure
      security:
        - OAuthV2B2B:
            - patient/Procedure.read
    put:
      tags:
        - Procedure
      description: 'Update an existing Procedure by its id (or create it if it is new).<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Update Procedure
      security:
        - OAuthV2B2B:
            - patient/Procedure.write
    delete:
      tags:
        - Procedure
      description: 'The delete interaction removes an existing Procedure.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Delete Procedure
      security:
        - OAuthV2B2B:
            - patient/Procedure.write
  '/Procedure/{id}/_history':
    get:
      tags:
        - Procedure
      description: 'It retrieves the history of a particular Procedure identified by the given id in path.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedure History
      security:
        - OAuthV2B2B:
            - patient/Procedure.read
  /Procedure/_history:
    get:
      tags:
        - Procedure
      description: 'It retrieves the history of all resources of Procedure.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedures History
      security:
        - OAuthV2B2B:
            - patient/Procedure.read
  '/Procedure/{id}/_history/{vid}':
    get:
      tags:
        - Procedure
      description: 'This interaction preforms a version specific read of Procedure resource.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedure Version Read
      security:
        - OAuthV2B2B:
            - patient/Procedure.read
  /Procedure/$meta:
    get:
      tags:
        - Procedure
      description: 'Retrieves a summary of the profiles, tags, and security labels for Procedures.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedures Metadata
      security:
        - OAuthV2B2B:
            - patient/Procedure.read
  '/Procedure/{id}/$meta':
    get:
      tags:
        - Procedure
      description: 'Retrieves a summary of the profiles, tags, and security labels for given Procedure resource.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedure Metadata
      security:
        - OAuthV2B2B:
            - patient/Procedure.read
  '/Procedure/{id}/_history/{vid}/$meta':
    get:
      tags:
        - Procedure
      description: 'Retrieves a summary of the profiles, tags, and security labels for given version of the Procedure.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedure Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Procedure.read
  '/Procedure/{id}/{type}':
    get:
      tags:
        - Procedure
      description: 'Search the specified resource type in Procedure compartment.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: ' Compartment Search'
      security:
        - OAuthV2B2B:
            - patient/Procedure.read
  /Procedure/_search:
    post:
      tags:
        - Procedure
      description: 'This interaction searches a set of Procedures based on some filter criteria. Search interactions take a series of parameters of name''=''value pairs encoded as an application/x-www-form-urlencoded submission for a POST.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Procedures Search using POST
      security:
        - OAuthV2B2B:
            - patient/Procedure.read
  '/Procedure/{id}/$meta-add':
    post:
      tags:
        - Procedure
      description: 'Add a metadata info Procedure with specified id.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Add Procedure metadata
      security:
        - OAuthV2B2B:
            - patient/Procedure.write
  '/Procedure/{id}/_history/{vid}/$meta-add':
    post:
      tags:
        - Procedure
      description: 'Add metadata info to specified Procedure resource.<p><a href = ''https://www.hl7.org/fhir/procedure.html''>FHIR documentation for Procedure.</a></p>'
      operationId: Add Procedure Version based Metadata
      security:
        - OAuthV2B2B:
            - patient/Procedure.write
components:
  securitySchemes:
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://org-env.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            patient/Procedure.read: Read permissions for Procedure demographics.
            patient/Procedure.write: Write permissions for Procedure demographics.
